name: build

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: setup alpine
        uses: jirutka/setup-alpine@v1
        
      - name: setup pages
        id: pages
        uses: actions/configure-pages@v1
        
      - name: install packages
        shell: alpine.sh --root {0}
        run: |
          apk add lowdown
        
      - name: build site
        shell: alpine.sh {0}
        run: |
          sh bin/build.sh
        
      - name: upload pages
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: _pages
