name: build

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: image: alpine:3.14
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup alpine
        uses: jirutka/setup-alpine@v1
      
      - name: setup pages
        id: pages
        uses: actions/configure-pages@v1
      
      - name: build site
        run: |
          ls -ls
        shell: alpine.sh --root {0}
