name: build

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup alpine
        uses: jirutka/setup-alpine@v1
      
      - name: setup pages
        id: pages
        uses: actions/configure-pages@v1
      
      - name: build site
        run: |
          apk add lowdown
          sh bin/build.sh
        shell: alpine.sh --root {0}
